# action.yml
name: 'OpenAPI Codegen CLI'
description: 'Run OpenAPI Codegen with Github Actions'
branding:
    icon: code
    color: green
runs:
  using: 'docker'
  image: 'docker://openapitools/openapi-generator-cli'
  args:
  - ${{ inputs.action }}
  - '-i'
  - ${{ inputs.input }}
  - '-g'
  - ${{ inputs.language }}
inputs:
  language:
    description: Swagger language
    required: true
  input:
    description: Swagger file
    required: true
  action:
    description: openapi-generator-cli action
    required: true
